### ISSUE TITLE
The k-value problem

### ISSUE THREAD

**Issue by ANGLE404** [genbing99/SoftNet-SpotME#14]
------ Computing k ------
Traceback (most recent call last):
  File "d:/HuaweiMoveData/Users/ANJIAQI/Desktop/code/SoftNet-SpotME-main/main.py", line 63, in <module>
    main(config)
  File "d:/HuaweiMoveData/Users/ANJIAQI/Desktop/code/SoftNet-SpotME-main/main.py", line 32, in main
    k = cal_k(dataset_name, expression_type, final_samples)
  File "d:\HuaweiMoveData\Users\ANJIAQI\Desktop\code\SoftNet-SpotME-main\load_label.py", line 98, in cal_k
    N=total_duration/len(samples)
ZeroDivisionError: division by zero

总是出现这个错误，应该如何解决

**Comment by genbing99** [comment]
It seems that the length of samples is zero. Could you please verify that the dataset is in its original form?

**Comment by genbing99** [comment]
Closing due to inactivity.
